export const ADD_RECIPE_REQUEST = "ADD_RECIPE_REQUEST";
export const ADD_RECIPE_SUCCESS = "ADD_RECIPE_SUCCESS";
export const ADD_RECIPE_ERROR = "ADD_RECIPE_ERROR";

export const GET_RECIPE_REQUEST = "GET_RECIPE_REQUEST";
export const GET_RECIPE_SUCCESS = "GET_RECIPE_SUCCESS";
export const GET_RECIPE_ERROR = "GET_RECIPE_ERROR";

export const SAVE_PRODUCT_REQUEST = "SAVE_PRODUCT_REQUEST";
export const SAVE_PRODUCT_SUCCESS = "SAVE_PRODUCT_SUCCESS";
export const SAVE_PRODUCT_ERROR = "SAVE_PRODUCT_ERROR";

export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";

export const GET_MEASUREMENTS_REQUEST = "GET_MEASUREMENTS_REQUEST";
export const GET_MEASUREMENTS_SUCCESS = "GET_MEASUREMENTS_SUCCESS";
export const GET_MEASUREMENTS_ERROR = "GET_MEASUREMENTS_ERROR";
